### ISSUE TITLE
 cannot import name 'GuessedAtParserWarning' from 'bs4'

### ISSUE THREAD

**Issue by CharlesGodwin** [snoopyjc/xls2xlsx#10]
* xls2xlsx version: 0.1.5
* Python version: 3.7.3
* Operating System:Windows 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I was attempting to convert an .xls file 
Attached is a full pip show of all dependencies and the xls file 

### What I Did

```

xls2xlsx ARN1-2013Jun16.xls

Traceback (most recent call last):
  File "c:\users\charl\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\charl\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\charl\AppData\Local\Programs\Python\Python37\Scripts\xls2xlsx.exe\__main__.py", line 4, in <module>
  File "c:\users\charl\appdata\local\programs\python\python37\lib\site-packages\xls2xlsx\__init__.py", line 3, in <module>
    from .htmlxls2xlsx import HTMLXLS2XLSX
  File "c:\users\charl\appdata\local\programs\python\python37\lib\site-packages\xls2xlsx\htmlxls2xlsx.py", line 3, in <module>
    from bs4 import GuessedAtParserWarnin

ImportError: cannot import name 'GuessedAtParserWarning' from 'bs4' (c:\users\charl\appdata\local\programs\python\python37\lib\site-packages\bs4\__init__.py)

```
[xls2xlsx.zip](https://github.com/snoopyjc/xls2xlsx/files/5874153/xls2xlsx.zip)

**Comment by snoopyjc** [comment]
Try using beautifulsoup4==4.9.1

Let me know what version you have and I'll see what I need to do in order to make it work with that version.

**Comment by CharlesGodwin** [comment]
I moved on to another solution.
